# Railway configuration for backend
[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python email_api.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "5001" 